# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='commodityinfo',
            fields=[
                ('C_ID', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('C_Name', models.CharField(max_length=256)),
                ('C_Cost', models.DecimalField(decimal_places=2, max_digits=100)),
                ('C_Price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('C_Weight', models.DecimalField(decimal_places=2, max_digits=20)),
                ('C_Packaging', models.CharField(choices=[('Can', 'Can'), ('Bottle', 'Bottle'), ('Box', 'Box'), ('Bag', 'Bag'), ('Cup', 'Cup')], max_length=20)),
                ('C_Category', models.CharField(choices=[('Nuts', 'Nuts'), ('Bread', 'Bread'), ('Beverage', 'Beverage'), ('InstanNoodles', 'InstanNoodles')], max_length=20)),
                ('C_Capacity', models.IntegerField()),
                ('totalquantity', models.IntegerField()),
            ],
            options={
                'db_table': 'commodityinfo',
                'managed': False,
            },
        ),
    ]
