# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_ID', models.CharField(max_length=256)),
                ('C_Name', models.CharField(max_length=256)),
                ('C_Cost', models.DecimalField(decimal_places=2, max_digits=100)),
                ('C_Price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('C_Weight', models.DecimalField(decimal_places=2, max_digits=20)),
                ('C_Packaging', models.CharField(choices=[('Can', 'Can'), ('Bottle', 'Bottle'), ('Box', 'Box'), ('Bag', 'Bag'), ('Cup', 'Cup')], max_length=20)),
                ('C_Category', models.CharField(choices=[('Nuts', 'Nuts'), ('Bread', 'Bread'), ('Beverage', 'Beverage'), ('InstanNoodles', 'InstanNoodles')], max_length=20)),
                ('C_Capacity', models.IntegerField()),
            ],
            options={
                'db_table': 'Commodity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('M_Id', models.CharField(max_length=256)),
                ('M_Name', models.CharField(max_length=256)),
                ('M_Phone', models.CharField(max_length=256)),
                ('M_Address', models.CharField(max_length=256)),
                ('M_Age', models.IntegerField()),
            ],
            options={
                'db_table': 'Monitor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_ID', models.CharField(max_length=256)),
                ('P_Name', models.CharField(max_length=256)),
                ('S_Address', models.CharField(max_length=256)),
                ('S_Phone', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Provider',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PurchasingAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PA_ID', models.CharField(max_length=256)),
                ('PA_Name', models.CharField(max_length=256)),
                ('PA_Age', models.IntegerField()),
                ('PA_Phone', models.CharField(max_length=20)),
                ('PA_Address', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'PurchasingAgent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Put',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PA_ID', models.CharField(max_length=256)),
                ('S_ID', models.CharField(max_length=256)),
                ('C_ID', models.CharField(max_length=256)),
                ('PutDate', models.DateField()),
                ('Quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'Put',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Saler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_ID', models.CharField(max_length=256)),
                ('S_Name', models.CharField(max_length=256)),
                ('S_Salary', models.DecimalField(decimal_places=2, max_digits=20)),
                ('S_Age', models.IntegerField()),
                ('S_Phone', models.CharField(max_length=20)),
                ('S_Address', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'Saler',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Supervise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('M_ID', models.CharField(max_length=256)),
                ('W_ID', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'Supervise',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('W_ID', models.CharField(max_length=256)),
                ('W_Name', models.CharField(max_length=256)),
                ('W_Address', models.CharField(max_length=256)),
                ('W_Capacity', models.IntegerField()),
            ],
            options={
                'db_table': 'Warehouse',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WarehouseStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('W_ID', models.CharField(max_length=256)),
                ('C_ID', models.CharField(max_length=256)),
                ('Quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'WarehouseStorage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OutRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_ID', models.CharField(max_length=256)),
                ('C_ID', models.CharField(max_length=256)),
                ('SellDate', models.DateField()),
                ('TotalPrice', models.DecimalField(decimal_places=2, max_digits=30)),
                ('Quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
