# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 09:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commodity_server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outrecord',
            name='TotalPrice',
        ),
    ]
