# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity_server', '0002_remove_outrecord_totalprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outrecord',
            name='id',
        ),
        migrations.AddField(
            model_name='outrecord',
            name='Out_ID',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
