# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 09:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commodity_server', '0003_auto_20170911_1746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outrecord',
            options={'managed': False},
        ),
    ]
