# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 06:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commodity_server', '0004_auto_20170911_1756'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='outrecord',
            table='OutRecord',
        ),
    ]
